# Generated by Django 4.0.1 on 2022-05-25 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Recipe', '0002_remove_food_food_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='food_for_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='food',
            name='food_ingredient_summary',
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='food_name',
            field=models.CharField(db_index=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='food_summary',
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
    ]
