# Generated by Django 4.0.1 on 2022-05-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0005_food_recipe_recipe_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_preview',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
