# Generated by Django 4.0.1 on 2022-05-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitness',
            name='fitness_preview',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
