# Generated by Django 4.0.1 on 2022-06-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0004_alter_fitness_fitness_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitness',
            name='fitness_present',
        ),
        migrations.AlterField(
            model_name='fitness',
            name='fitness_summary',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
