# Generated by Django 4.0.1 on 2022-06-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0005_remove_fitness_fitness_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitness',
            name='fitness_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
