# Generated by Django 4.0.1 on 2022-06-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0006_fitness_fitness_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness',
            name='fitness_preview',
            field=models.ImageField(blank=True, null=True, upload_to='article/fit_photo'),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='fitness_summary',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
