# Generated by Django 4.0.1 on 2022-01-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0002_rename_persons_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purposes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_name', models.CharField(db_index=True, max_length=100)),
                ('day_begin', models.DateField(blank=True, null=True)),
                ('day_end', models.DateField(blank=True, null=True)),
                ('persons_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purposes_for_user', to='Person.person')),
            ],
        ),
    ]
