# Generated by Django 4.0.1 on 2022-05-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0005_food_recipe_recipe_foods'),
        ('Nutrients', '0002_remove_foodnutrients_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodnutrients',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nutrients_for_food', to='Recipe.food'),
        ),
    ]
