# Generated by Django 4.0.1 on 2022-06-06 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrients', '0004_alter_foodnutrients_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodnutrients',
            name='nutrientInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nutrients', to='Nutrients.nutrients'),
        ),
    ]
