# Generated by Django 4.0.1 on 2022-05-25 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0017_alter_post_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(db_index=True, max_length=200)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_for_user', to=settings.AUTH_USER_MODEL)),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='Blog.post')),
            ],
        ),
    ]
