# Generated by Django 4.0.1 on 2022-04-03 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_name', models.CharField(db_index=True, max_length=100)),
                ('unitName', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodNutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('nutrientInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nutrients_for_food', to='Blog.nutrients')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='nutrients',
            field=models.ManyToManyField(to='Blog.FoodNutrients'),
        ),
    ]
