# Generated by Django 4.0.1 on 2022-04-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_remove_food_food_kcal_food_food_ingredient_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrients',
            name='rank',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
