# Generated by Django 4.0.1 on 2022-04-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_nutrients_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_ingredient_summary',
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_summary',
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='nutrient_name',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='unitName',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
