# Generated by Django 4.0.1 on 2022-04-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_food_food_ingredient_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='person_id',
            new_name='post_author',
        ),
    ]
