# Generated by Django 4.0.1 on 2022-04-04 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0003_alter_person_person_photo'),
        ('Blog', '0007_rename_rank_nutrients_nutrient_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness',
            name='fitness_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fitness_for_user', to='Person.person'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='food_for_user', to='Person.person'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='post_for_user', to='Person.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_for_user', to='Person.person'),
        ),
    ]
