# Generated by Django 4.0.1 on 2022-05-23 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_recipe_recipe_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='nutrients',
        ),
        migrations.AddField(
            model_name='foodnutrients',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nutrients_for_food', to='Blog.food'),
        ),
    ]
