# Generated by Django 4.0.1 on 2022-05-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0001_initial'),
        ('Blog', '0011_remove_food_nutrients_foodnutrients_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_fitness',
            field=models.ManyToManyField(to='Fitness.Fitness'),
        ),
        migrations.DeleteModel(
            name='Fitness',
        ),
    ]
