# Generated by Django 4.0.1 on 2022-05-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
        ('Blog', '0014_post_post_fitness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodnutrients',
            name='food',
        ),
        migrations.RemoveField(
            model_name='foodnutrients',
            name='nutrientInfo',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_author',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_foods',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_recipes',
            field=models.ManyToManyField(to='Recipe.Recipe'),
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='FoodNutrients',
        ),
        migrations.DeleteModel(
            name='Nutrients',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
