# Generated by Django 4.0.1 on 2022-05-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0008_alter_food_food_preview'),
        ('Fitness', '0004_alter_fitness_fitness_preview'),
        ('Blog', '0024_post_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_fitness',
            field=models.ManyToManyField(blank=True, to='Fitness.Fitness'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_recipes',
            field=models.ManyToManyField(blank=True, to='Recipe.Recipe'),
        ),
    ]
