# Generated by Django 4.0.1 on 2022-06-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0025_alter_post_post_fitness_alter_post_post_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='article/blog_images'),
        ),
    ]
