# Generated by Django 4.0.1 on 2022-01-12 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0002_rename_persons_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_name', models.CharField(db_index=True, max_length=100)),
                ('fitness_kcal', models.IntegerField(blank=True, null=True)),
                ('fitness_time', models.IntegerField(blank=True, null=True)),
                ('fitness_summary', models.CharField(db_index=True, max_length=200)),
                ('fitness_present', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(db_index=True, max_length=100)),
                ('food_kcal', models.IntegerField(blank=True, null=True)),
                ('food_summary', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(db_index=True, max_length=100)),
                ('recipe_time', models.IntegerField(blank=True, null=True)),
                ('recipe_summary', models.CharField(db_index=True, max_length=1000)),
                ('recipe_foods', models.ManyToManyField(to='Blog.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(db_index=True, max_length=100)),
                ('post_summary', models.CharField(db_index=True, max_length=10000)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('person_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post_for_user', to='Person.person')),
                ('post_fitness', models.ManyToManyField(to='Blog.Fitness')),
                ('post_recipes', models.ManyToManyField(to='Blog.Recipe')),
                ('post_tags', models.ManyToManyField(to='Blog.Tags')),
            ],
        ),
    ]
