# Generated by Django 4.0.1 on 2022-04-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_nutrients_foodnutrients_food_nutrients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_kcal',
        ),
        migrations.AddField(
            model_name='food',
            name='food_ingredient_summary',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_summary',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
