# Generated by Django 4.0.1 on 2022-05-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_alter_post_post_fitness_delete_fitness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_fitness',
        ),
    ]
