# Generated by Django 4.0.1 on 2022-05-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_post_post_type_alter_post_post_fitness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('all', 'Все новости'), ('fitness', 'Фитнес и спорт'), ('diet', 'Питание ')], default='all', help_text='Тип новостей', max_length=50),
        ),
    ]
