# Generated by Django 4.0.1 on 2022-05-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0022_post_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_author',
        ),
    ]
