# Generated by Django 4.0.1 on 2022-05-25 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_name', models.CharField(db_index=True, max_length=100)),
                ('fitness_kcal', models.IntegerField(blank=True, null=True)),
                ('fitness_time', models.IntegerField(blank=True, null=True)),
                ('fitness_summary', models.CharField(db_index=True, max_length=200)),
                ('fitness_present', models.ImageField(blank=True, null=True, upload_to='')),
                ('fitness_author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fitness_for_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
