# Generated by Django 4.0.1 on 2022-01-11 18:13

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(db_index=True, max_length=100)),
                ('person_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('summary', models.CharField(db_index=True, max_length=1000, null=True)),
                ('person_gender', models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина'), ('other', 'Другие')], default='study', help_text='Половая принадлежность', max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('person_height', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['person_name'],
            },
        ),
        migrations.CreateModel(
            name='PersonHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_check', models.DateField(blank=True, null=True)),
                ('person_weight', models.IntegerField(blank=True, null=True)),
                ('person_pulse', models.IntegerField(blank=True, null=True)),
                ('person_steps_per_day', models.IntegerField(blank=True, null=True)),
                ('persons_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='health_for_user', to='Person.persons')),
            ],
            options={
                'ordering': ['date_of_check'],
            },
        ),
    ]
