# Generated by Django 4.0.1 on 2022-05-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0009_person_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_name',
        ),
    ]
