# Generated by Django 4.0.1 on 2022-05-28 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0012_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personphoto',
            name='person_photo',
            field=models.FileField(null=True, upload_to='article/profile_photo', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
