# Generated by Django 4.0.1 on 2022-06-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0014_person_group_of_study_person_place_of_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='group_of_study',
        ),
        migrations.AddField(
            model_name='person',
            name='release_date',
            field=models.CharField(db_index=True, max_length=1000, null=True),
        ),
    ]
