# Generated by Django 4.0.1 on 2022-06-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0015_remove_person_group_of_study_person_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
