# Generated by Django 4.0.1 on 2022-05-25 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(db_index=True, max_length=1000)),
                ('food_summary', models.CharField(db_index=True, max_length=500, null=True)),
                ('food_ingredient_summary', models.CharField(db_index=True, max_length=500, null=True)),
                ('food_author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='food_for_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(db_index=True, max_length=100)),
                ('recipe_time', models.IntegerField(blank=True, null=True)),
                ('recipe_summary', models.CharField(db_index=True, max_length=1000)),
                ('recipe_author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_for_user', to=settings.AUTH_USER_MODEL)),
                ('recipe_foods', models.ManyToManyField(to='Recipe.Food')),
            ],
        ),
    ]
