# Generated by Django 4.0.1 on 2022-05-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_author',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_ingredient_summary',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_summary',
        ),
    ]
