# Generated by Django 4.0.1 on 2022-05-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrients', '0002_remove_foodnutrients_food'),
        ('Recipe', '0003_food_food_author_food_food_ingredient_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_foods',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
