# Generated by Django 4.0.1 on 2022-05-25 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Purpose', '0002_rename_persons_data_purposes_person_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurposePause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_pause', models.DateField(blank=True, null=True)),
                ('pause_reason', models.CharField(db_index=True, max_length=100)),
                ('purpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purpose', to='Purpose.purposes')),
            ],
        ),
    ]
