# Generated by Django 4.0.1 on 2022-05-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodnutrients',
            name='food',
        ),
    ]
