# Generated by Django 4.0.1 on 2022-06-06 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0008_alter_food_food_preview'),
        ('Nutrients', '0003_foodnutrients_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodnutrients',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrients_for_food', to='Recipe.food'),
        ),
    ]
