# Generated by Django 4.0.1 on 2022-06-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Achievement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='article/achievement_photo'),
        ),
    ]
