# Generated by Django 4.0.1 on 2022-05-25 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0003_alter_person_person_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=1000)),
                ('complete_stage', models.BooleanField(db_index=True, default=False)),
                ('task_author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='todo_for_user', to='Person.person')),
            ],
        ),
    ]
