# Generated by Django 4.0.1 on 2022-06-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0003_alter_todotask_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='task_summary',
            field=models.CharField(db_index=True, default='test', max_length=1000),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='task_name',
            field=models.CharField(db_index=True, default='Test', max_length=100),
        ),
    ]
