# Generated by Django 4.0.1 on 2022-06-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0004_todotask_task_summary_alter_todotask_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='task_name',
            field=models.CharField(db_index=True, default='Error', max_length=100),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='task_summary',
            field=models.CharField(db_index=True, default='error', max_length=1000),
        ),
    ]
