# Generated by Django 4.0.1 on 2022-04-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_rename_persons_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_photo',
            field=models.ImageField(blank=True, null=True, upload_to='article'),
        ),
    ]
