# Generated by Django 4.0.1 on 2022-05-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0003_alter_person_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo'),
        ),
    ]
