# Generated by Django 4.0.1 on 2022-05-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0010_alter_person_options_remove_person_person_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_photo', models.ImageField(blank=True, null=True, upload_to='article/profile_photo')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_photo',
        ),
    ]
