# Generated by Django 4.0.1 on 2022-05-28 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0011_personphoto_remove_person_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_for_user', to='Person.personphoto'),
        ),
    ]
