# Generated by Django 4.0.1 on 2022-06-05 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Achievement', '0002_alter_achievement_photo'),
        ('Person', '0018_alter_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personhealth',
            name='persons_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='health_for_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PersonAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='Achievement.achievement')),
                ('persons_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievement_for_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
