# Generated by Django 4.0.1 on 2022-06-21 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0022_alter_person_country_alter_person_person_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personhealth',
            name='date_of_check',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 21, 13, 54, 55, 168783), null=True),
        ),
    ]
