# Generated by Django 4.0.1 on 2022-06-21 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0023_alter_personhealth_date_of_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personhealth',
            name='date_of_check',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 21, 13, 56, 28, 165974), null=True),
        ),
    ]
