# Generated by Django 4.0.1 on 2022-06-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0024_alter_personhealth_date_of_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personhealth',
            name='date_of_check',
            field=models.DateField(blank=True, null=True),
        ),
    ]
