# Generated by Django 4.0.1 on 2022-06-15 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0004_alter_fitness_fitness_preview'),
        ('UserWorkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercise_text',
            field=models.CharField(blank=True, help_text='user_exercise', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_from_blog', to='Fitness.fitness'),
        ),
    ]
