# Generated by Django 4.0.1 on 2022-06-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserWorkout', '0002_workout_exercise_text_alter_workout_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='day',
            field=models.CharField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1, help_text='День недели', max_length=10),
        ),
    ]
