# Generated by Django 4.0.1 on 2022-05-26 07:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0017_alter_post_post_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Favourite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='Favourite',
        ),
    ]
